//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetManagmentEquipmentSoftwareAsset
    {
        public System.Guid SAId { get; set; }
        public System.Guid AMEId { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public string LicenseType { get; set; }
        public string Category { get; set; }
        public string IsActive { get; set; }
        public string SASoftwareId { get; set; }
        public string SAOwner { get; set; }
        public string SAPersonResponsible { get; set; }
        public string SACriticality { get; set; }
        public string SAOperatingSystem { get; set; }
        public string SAOSPatchVersion { get; set; }
    }
}
