//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetManagmentEquipmentOTList
    {
        public System.Guid OTId { get; set; }
        public System.Guid AMEId { get; set; }
        public string OTEquipment { get; set; }
        public string OTLocation { get; set; }
        public string OTMake { get; set; }
        public string OTModel { get; set; }
        public string OTType { get; set; }
        public string OTSerialNo { get; set; }
        public string OTWorkingCondition { get; set; }
        public string OTLastServiced { get; set; }
        public string OTRemark { get; set; }
        public string OTHardwareId { get; set; }
        public string OTOwner { get; set; }
        public string OTPersonResponsible { get; set; }
        public string OTCriticality { get; set; }
        public string OTOperatingSystem { get; set; }
        public string OTOSPatchVersion { get; set; }
    }
}
