//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetManagmentEquipmentITList
    {
        public System.Guid ITId { get; set; }
        public System.Guid AMEId { get; set; }
        public string ITEquipment { get; set; }
        public string ITLocation { get; set; }
        public string ITMake { get; set; }
        public string ITModel { get; set; }
        public string ITType { get; set; }
        public string ITSerialNo { get; set; }
        public string ITWorkingCondition { get; set; }
        public string ITLastServiced { get; set; }
        public string ITRemark { get; set; }
        public string ITHardwareId { get; set; }
        public string ITOwner { get; set; }
        public string ITPersonResponsible { get; set; }
        public string ITCriticality { get; set; }
        public string ITOperatingSystem { get; set; }
        public string ITOSPatchVersion { get; set; }
    }
}
