//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditNote
    {
        public long AuditNotesId { get; set; }
        public Nullable<long> InternalAuditFormId { get; set; }
        public string Number { get; set; }
        public string Type { get; set; }
        public string BriefDescription { get; set; }
        public string Reference { get; set; }
        public string FullDescription { get; set; }
        public string CorrectiveAction { get; set; }
        public string PreventativeAction { get; set; }
        public string Rank { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> TimeScale { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Ship { get; set; }
        public Nullable<bool> IsResolved { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<System.Guid> UniqueFormID { get; set; }
        public Nullable<System.Guid> NotesUniqueID { get; set; }
        public Nullable<int> Priority { get; set; }
        public int isDelete { get; set; }
        public Nullable<System.Guid> AssignTo { get; set; }
    }
}
