//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditNotesCommentsFile
    {
        public long CommentFileID { get; set; }
        public Nullable<long> CommentsID { get; set; }
        public Nullable<long> AuditNoteID { get; set; }
        public string FileName { get; set; }
        public string StorePath { get; set; }
        public Nullable<System.Guid> CommentUniqueID { get; set; }
        public Nullable<System.Guid> CommentFileUniqueID { get; set; }
    }
}
