//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CASHIP_WebGUIEntities : DbContext
    {
        public CASHIP_WebGUIEntities()
            : base("name=CASHIP_WebGUIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SM_ACCOUNTCODE> SM_ACCOUNTCODE { get; set; }
    
        public virtual ObjectResult<sp_GetReportsData_Result1> sp_GetReportsData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetReportsData_Result1>("sp_GetReportsData");
        }
    }
}
