//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPositionReport
    {
        public long DPRID { get; set; }
        public Nullable<int> ShipNo { get; set; }
        public string ShipCode { get; set; }
        public string ShipName { get; set; }
        public string ReportCreated { get; set; }
        public Nullable<int> VoyageNo { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<bool> Anchored { get; set; }
        public Nullable<double> AverageSpeed { get; set; }
        public Nullable<double> DistanceMade { get; set; }
        public string NextPort { get; set; }
        public string EstimatedArrivalDateEcoSpeed { get; set; }
        public string EstimatedArrivalTimeEcoSpeed { get; set; }
        public string EstimatedArrivalDateFullSpeed { get; set; }
        public string EstimatedArrivalTimeFullSpeed { get; set; }
        public Nullable<double> FuelOil { get; set; }
        public Nullable<double> DieselOil { get; set; }
        public Nullable<double> SulphurFuelOil { get; set; }
        public Nullable<double> SulphurDieselOil { get; set; }
        public Nullable<double> FreshWater { get; set; }
        public Nullable<double> LubeOil { get; set; }
        public Nullable<double> Sludge { get; set; }
        public Nullable<double> DirtyOil { get; set; }
        public Nullable<double> Pitch { get; set; }
        public Nullable<double> EngineLoad { get; set; }
        public Nullable<double> HighCylExhTemp { get; set; }
        public Nullable<double> ExhGasTempAftTurboChrg { get; set; }
        public Nullable<double> OilCunsum { get; set; }
        public string WindDirection { get; set; }
        public string WindForce { get; set; }
        public string SeaState { get; set; }
        public string SwellDirection { get; set; }
        public Nullable<double> SwellHeight { get; set; }
        public Nullable<double> DraftAft { get; set; }
        public Nullable<double> DraftForward { get; set; }
        public string Remarks { get; set; }
        public string ToEmail { get; set; }
        public string CCEmail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public string CargoType { get; set; }
        public string CreatedBy { get; set; }
    }
}
