//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyCargoReport
    {
        public long DCRID { get; set; }
        public Nullable<int> ShipNo { get; set; }
        public string ShipName { get; set; }
        public string ReportCreated { get; set; }
        public Nullable<int> VoyageNo { get; set; }
        public string PortName { get; set; }
        public Nullable<double> NoOfGangsEmployed { get; set; }
        public Nullable<double> NoOfShipsCranesInUse { get; set; }
        public Nullable<double> QuantityOfCargoLoaded { get; set; }
        public Nullable<double> TotalCargoLoaded { get; set; }
        public Nullable<double> CargoRemaining { get; set; }
        public Nullable<double> FuelOil { get; set; }
        public Nullable<double> DieselOil { get; set; }
        public Nullable<double> SulphurFuelOil { get; set; }
        public Nullable<double> SulphurDieselOil { get; set; }
        public Nullable<double> Sludge { get; set; }
        public Nullable<double> DirtyOil { get; set; }
        public string ETCDate { get; set; }
        public string ETCTime { get; set; }
        public string NextPort { get; set; }
        public string Remarks { get; set; }
        public string ToEmail { get; set; }
        public string CCEmail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public string CargoType { get; set; }
        public string CreatedBy { get; set; }
    }
}
