//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartureReport
    {
        public long DRID { get; set; }
        public Nullable<int> ShipNo { get; set; }
        public string ShipName { get; set; }
        public string ReportCreated { get; set; }
        public Nullable<int> VoyageNo { get; set; }
        public string PortName { get; set; }
        public string DateCargoOperations { get; set; }
        public string TimeCargoOperations { get; set; }
        public string CargoOnBoard { get; set; }
        public string CargoLoaded { get; set; }
        public string POBDate { get; set; }
        public string POBTime { get; set; }
        public string DepartureDate { get; set; }
        public string DepartureTime { get; set; }
        public string POffDate { get; set; }
        public string POffTime { get; set; }
        public string NoOfTugs { get; set; }
        public Nullable<double> FuelOil { get; set; }
        public Nullable<double> DieselOil { get; set; }
        public Nullable<double> SulphurFuelOil { get; set; }
        public Nullable<double> SulphurDieselOil { get; set; }
        public string NextPort { get; set; }
        public string ETADate { get; set; }
        public string ETATime { get; set; }
        public string IntendedRoute { get; set; }
        public string Remarks { get; set; }
        public string ToEmail { get; set; }
        public string CCEmail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<double> DraftAFT { get; set; }
        public Nullable<double> DraftFWD { get; set; }
    }
}
