//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackForm
    {
        public System.Guid Id { get; set; }
        public string ShipName { get; set; }
        public string ShipCode { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsMailSent { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public string AttachmentPath { get; set; }
        public string AttachmentFileName { get; set; }
        public string FeedbackBy { get; set; }
    }
}
