//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FSTOInspection
    {
        public long FSTOInspectionId { get; set; }
        public Nullable<System.Guid> UniqueFormID { get; set; }
        public Nullable<decimal> FormVersion { get; set; }
        public Nullable<System.DateTime> TravelStartedOn { get; set; }
        public Nullable<System.DateTime> EmbarkedOn { get; set; }
        public Nullable<System.DateTime> DisembarkedOn { get; set; }
        public Nullable<System.DateTime> TravelEndedOn { get; set; }
        public string Location { get; set; }
        public string ShipCode { get; set; }
        public string PurposeOfVisit { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
