//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIRDeficiency
    {
        public int DeficienciesID { get; set; }
        public Nullable<long> GIRFormID { get; set; }
        public int No { get; set; }
        public Nullable<System.DateTime> DateRaised { get; set; }
        public string Deficiency { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Ship { get; set; }
        public Nullable<bool> IsClose { get; set; }
        public string ReportType { get; set; }
        public string FileName { get; set; }
        public string StorePath { get; set; }
        public string SIRNo { get; set; }
        public string ItemNo { get; set; }
        public string Section { get; set; }
        public Nullable<System.Guid> UniqueFormID { get; set; }
        public Nullable<int> isDelete { get; set; }
        public Nullable<System.Guid> DeficienciesUniqueID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.Guid> AssignTo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual GeneralInspectionReport GeneralInspectionReport { get; set; }
    }
}
