//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIRDeficienciesCommentFile
    {
        public long GIRCommentFileID { get; set; }
        public Nullable<long> NoteID { get; set; }
        public Nullable<long> DeficienciesID { get; set; }
        public string FileName { get; set; }
        public string StorePath { get; set; }
        public string IsUpload { get; set; }
        public Nullable<System.Guid> NoteUniqueID { get; set; }
        public Nullable<System.Guid> CommentFileUniqueID { get; set; }
    }
}
