//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIRDeficienciesFile
    {
        public int GIRDeficienciesFileID { get; set; }
        public Nullable<long> DeficienciesID { get; set; }
        public string FileName { get; set; }
        public string StorePath { get; set; }
        public Nullable<System.Guid> DeficienciesUniqueID { get; set; }
        public System.Guid DeficienciesFileUniqueID { get; set; }
    }
}
