//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIRDeficienciesResolutionFile
    {
        public long GIRFileID { get; set; }
        public Nullable<long> GIRResolutionID { get; set; }
        public Nullable<long> DeficienciesID { get; set; }
        public string FileName { get; set; }
        public string StorePath { get; set; }
        public string IsUpload { get; set; }
        public Nullable<System.Guid> ResolutionUniqueID { get; set; }
        public Nullable<System.Guid> ResolutionFileUniqueID { get; set; }
    }
}
