//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIRDeficienciesNote
    {
        public long NoteID { get; set; }
        public Nullable<long> DeficienciesID { get; set; }
        public Nullable<long> GIRFormID { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<System.Guid> NoteUniqueID { get; set; }
        public Nullable<System.Guid> DeficienciesUniqueID { get; set; }
        public Nullable<int> isNew { get; set; }
    }
}
