//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIRRestandWorkHour
    {
        public int RestandWorkHoursID { get; set; }
        public Nullable<long> GIRFormID { get; set; }
        public string CrewmemberName { get; set; }
        public string RestAndWorkDetail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Ship { get; set; }
        public Nullable<System.Guid> UniqueFormID { get; set; }
    
        public virtual GeneralInspectionReport GeneralInspectionReport { get; set; }
    }
}
