//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoldVentilationRecordForm
    {
        public long HoldVentilationRecordFormId { get; set; }
        public string ShipName { get; set; }
        public string ShipCode { get; set; }
        public string Cargo { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string LoadingPort { get; set; }
        public Nullable<System.DateTime> LoadingDate { get; set; }
        public string DischargingPort { get; set; }
        public Nullable<System.DateTime> DischargingDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsSynced { get; set; }
    }
}
