//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoldVentilationRecordSheet
    {
        public long HoldVentilationRecordId { get; set; }
        public Nullable<long> HoldVentilationRecordFormId { get; set; }
        public Nullable<System.DateTime> HVRDate { get; set; }
        public Nullable<System.TimeSpan> HVRTime { get; set; }
        public string OUTDryBulb { get; set; }
        public string OUTWetBulb { get; set; }
        public string OUTDewPOint { get; set; }
        public string HODryBulb { get; set; }
        public string HOWetBulb { get; set; }
        public string HODewPOint { get; set; }
        public Nullable<bool> IsVentilation { get; set; }
        public Nullable<double> SeaTemp { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
