//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalAuditForm
    {
        public Nullable<System.Guid> UniqueFormID { get; set; }
        public Nullable<decimal> FormVersion { get; set; }
        public long InternalAuditFormId { get; set; }
        public Nullable<long> ShipId { get; set; }
        public string ShipName { get; set; }
        public string Location { get; set; }
        public string AuditNo { get; set; }
        public Nullable<bool> AuditTypeISM { get; set; }
        public Nullable<bool> AuditTypeISPS { get; set; }
        public Nullable<bool> AuditTypeMLC { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public Nullable<int> isDelete { get; set; }
        public int AuditType { get; set; }
        public bool IsAdditional { get; set; }
        public bool IsClosed { get; set; }
        public bool SavedAsDraft { get; set; }
    }
}
