//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MenuId { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string MenuText { get; set; }
        public string Description { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string Class { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public string MenuType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDefaultMenu { get; set; }
    }
}
