//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public Nullable<System.Guid> UniqueId { get; set; }
        public Nullable<System.Guid> UniqueDataId { get; set; }
        public string DataType { get; set; }
        public bool IsDraft { get; set; }
        public string Title { get; set; }
        public string DetailsURL { get; set; }
        public Nullable<System.Guid> FromUserId { get; set; }
        public Nullable<System.Guid> SentToUserId { get; set; }
        public Nullable<int> UserGroup { get; set; }
        public string NotificationType { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ReadDateTime { get; set; }
        public bool IsReminder { get; set; }
        public bool IsRead { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> ReadByUserId { get; set; }
    }
}
