//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenFileServicesReleaseNote
    {
        public long AppId { get; set; }
        public string AppVersion { get; set; }
        public string AppDescription { get; set; }
        public Nullable<System.DateTime> AppPublishDate { get; set; }
        public Nullable<int> NoOfFilesAffected { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
