//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskAssessmentFormHazard
    {
        public System.Guid Id { get; set; }
        public Nullable<long> HazardId { get; set; }
        public Nullable<long> RAFID { get; set; }
        public string Stage1Description { get; set; }
        public string Stage2Severity { get; set; }
        public string Stage2Likelihood { get; set; }
        public string Stage2RiskFactor { get; set; }
        public string Stage3Description { get; set; }
        public string Stage4Severity { get; set; }
        public string Stage4Likelihood { get; set; }
        public string Stage4RiskFactor { get; set; }
        public Nullable<System.Guid> RAFUniqueID { get; set; }
    }
}
