//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public Nullable<bool> IsReport { get; set; }
        public Nullable<bool> IsDocument { get; set; }
        public Nullable<bool> IsForm { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsSettings { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public Nullable<bool> IsDeficiencies { get; set; }
        public Nullable<bool> IsHelp { get; set; }
        public Nullable<bool> IsAbout { get; set; }
    }
}
