//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipAppDownloadLog
    {
        public System.Guid Id { get; set; }
        public string ShipCode { get; set; }
        public string PCName { get; set; }
        public string PCUniqueId { get; set; }
        public Nullable<long> OldAppId { get; set; }
        public Nullable<long> DownloadedAppId { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
    }
}
