//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ship
    {
        public int ShipID { get; set; }
        public string ShipName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ShipCode { get; set; }
        public Nullable<int> BuildYear { get; set; }
        public Nullable<int> IMONumber { get; set; }
        public string CallSign { get; set; }
        public Nullable<int> MMSI { get; set; }
        public Nullable<int> GrossTonnage { get; set; }
        public Nullable<int> NetTonnage { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Mobile { get; set; }
    }
}
