//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIRNote
    {
        public long NoteID { get; set; }
        public Nullable<long> SIRFormID { get; set; }
        public string Number { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> UniqueFormID { get; set; }
        public Nullable<System.Guid> NotesUniqueID { get; set; }
        public int IsDeleted { get; set; }
    }
}
