//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMRFormCrewMember
    {
        public long CrewMemberID { get; set; }
        public Nullable<long> SMRFormID { get; set; }
        public string Rank { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> ElectedAsSafety { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual SMRForm SMRForm { get; set; }
    }
}
