//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    
    public partial class sp_GetReportsData_Result1
    {
        public string PARENT_CODE { get; set; }
        public string PARENT_DESCR { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public string ACCOUNT_DESCR { get; set; }
        public Nullable<int> BUDGETYEAR { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<double> BUDGET_AMT { get; set; }
        public Nullable<double> MONTHLY_BUDGET { get; set; }
        public Nullable<int> USERID_BUDGETBY { get; set; }
        public Nullable<int> BUDGETID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string BASECURRENCY { get; set; }
        public Nullable<double> P01 { get; set; }
        public Nullable<double> P02 { get; set; }
        public Nullable<double> P03 { get; set; }
        public Nullable<double> P04 { get; set; }
        public Nullable<double> P05 { get; set; }
        public Nullable<double> P06 { get; set; }
        public Nullable<double> P07 { get; set; }
        public Nullable<double> P08 { get; set; }
        public Nullable<double> P09 { get; set; }
        public Nullable<double> P10 { get; set; }
        public Nullable<double> P11 { get; set; }
        public Nullable<double> P12 { get; set; }
        public Nullable<int> SITEID { get; set; }
    }
}
