//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public System.Guid UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserRole { get; set; }
        public Nullable<int> RoleOrder { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserGroup { get; set; }
        public int ShipFleetID { get; set; }
    }
}
