//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupMenuPermission
    {
        public System.Guid ID { get; set; }
        public int MenuID { get; set; }
        public int UserGroupID { get; set; }
        public bool IsActive { get; set; }
    }
}
