//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UID { get; set; }
        public string empnre01 { get; set; }
        public string empste01 { get; set; }
        public string fstnme01 { get; set; }
        public string surnme01 { get; set; }
        public string bthcnte01 { get; set; }
        public string fnce01 { get; set; }
        public string lane01 { get; set; }
        public string rsnewe01 { get; set; }
        public string sxee01 { get; set; }
        public Nullable<System.DateTime> bthdate01 { get; set; }
        public string nate01 { get; set; }
    }
}
