//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarisbrookeShippingAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIMSLogInfomation
    {
        public System.Guid VIMSID { get; set; }
        public Nullable<System.Guid> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<double> OldINVOICE_EXCHRATE { get; set; }
        public Nullable<System.DateTime> OldINVOICE_DATE { get; set; }
        public Nullable<double> NewINVOICE_EXCHRATE { get; set; }
        public Nullable<System.DateTime> NewINVOICE_DATE { get; set; }
        public Nullable<int> REQNINVOICEID { get; set; }
        public Nullable<int> VRID { get; set; }
        public string OLDAccountID { get; set; }
        public string NewAccountID { get; set; }
        public Nullable<System.DateTime> NewPoDate { get; set; }
        public Nullable<System.DateTime> OldPoDate { get; set; }
    }
}
